services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  server:
    image: blogapp-backend-dev
    volumes:
      - ./backend/:/usr/src/app
    environment:
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database
    container_name: blogapp-backend-dev
  app:
    image: blogapp-frontend-dev
    volumes:
      - ./frontend/:/usr/src/app
    container_name: blogapp-frontend-dev
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server

volumes:
  mongo_data: